[package]
org = "suwagath"
name = "user_crud_service"
version = "0.1.0"
distribution = "2201.12.6"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "mysql"
version = "1.13.0"

[[platform.java11.dependency]]
groupId = "com.mysql"
artifactId = "mysql-connector-j"
version = "8.0.33" 