[package]
org = "suwagath"
name = "bal_task"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "mysql"
version = "1.16.0"

[[platform.java11.dependency]]
groupId = "com.mysql"
artifactId = "mysql-connector-j"
version = "8.0.33"
